# action.yml
name: 'SemVer 2 Parse'
inputs:
  value_to_parse:
    description: 'Value to parse'
    required: false
    default: "${{ github.ref }}"
  run_id:
    description: 'GitHub run_id, typically defaulted so that it can be pulled from the github context'
    required: false
    default: "${{ github.run_id }}"
  run_number:
    description: 'GitHub run_number, typically defaulted so that it can be pulled from the github context'
    required: false
    default: "${{ github.run_number }}"
  run_attempt:
    description: 'GitHub run_attempt, typically defaulted so that it can be pulled from the github context'
    required: false
    default: "${{ github.run_attempt }}"
outputs:
  value_to_parse:
    description: 'The value to parse'
  semver_version:
    description: 'The fully matched version'
  major_version:
    description: 'The major version'
  minor_version:
    description: 'The minor version'
  patch_version:
    description: 'The patch version'
  pre_release_version:
    description: 'The pre-release version'
  build_metadata:
    description: 'The build metadata'
  major_minor_version:
    description: 'Returns any matching MajorVersion.MinorVersion pattern whether the input is valid SemVer or not.  Useful for development releases whee patch and prerelease values will be provided programmatically.'
  fallback_version:
    description: 'A best-effort at returning a SemVer-compatible version'
  dotnet_assembly_version:
    description: 'A version compatible with versioning .NET assemblies'
  nuget_version:
    description: 'A version compatible with versioning NuGet packages'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.run_id }}
    - ${{ inputs.run_number }}
    - ${{ inputs.run_attempt }}
    - ${{ inputs.value_to_parse }}
