# action.yml
name: 'SemVer 2 Parse'
description: 'Greet someone and record the time'
inputs:
  value_to_parse:  # id of input
    description: 'Value to parse'
    required: false
    default: "${{ github.ref }}"
outputs:
  value_to_parse:
    description: 'The value to parse'
  semver_version:
    description: 'The fully matched version'
  major_version:
    description: 'The major version'
  minor_version:
    description: 'The minor version'
  patch_version:
    description: 'The patch version'
  pre_release_version:
    description: 'The pre-release version'
  build_metadata:
    description: 'The build metadata'
  major_minor_version:
    description: 'Returns any matching MajorVersion.MinorVersion pattern whether the input is valid SemVer or not.  Useful for development releases whee patch and prerelease values will be provided programmatically.'
  fallback_version:
    description: 'A best-effort at returning a SemVer-compatible version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ github.run_id }}
    - ${{ github.run_number }}
    - ${{ github.run_attempt }}
    - ${{ inputs.value_to_parse }}
