# action.yml
name: 'SemVer 2 Parse'
description: 'Greet someone and record the time'
inputs:
  parseValue:  # id of input
    description: 'Value to parse'
    required: true
outputs:
  semVer: # id of output
    description: 'The fully matched version'
  semVerMajor: # id of output
    description: 'The major version'
  semVerMinor: # id of output
    description: 'The minor version'
  semVerPatch: # id of output
    description: 'The patch version'
  semVerPreRelease: # id of output
    description: 'The pre-release version'
  semVerBuildMetadata: # id of output
    description: 'The build metadata'
  majorMinorOnly: # id of output
    description: 'Returns any matching MajorVersion.MinorVersion pattern whether the input is valid SemVer or not.  Useful for development releases whee patch and prerelease values will be provided programmatically.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.parseValue }}
