name: Main Test

on: [push]

jobs:
  happy-path-with-v:
    runs-on: ubuntu-latest
    name: Happy Path with v prefix
    steps:
      - name: SemVer parse
        id: parse
        uses: NetChris-actions/parse-semver@1-init
        with:
          parseValue: 'v1.2.3'
      - name: Output full match
        run: echo ${{ steps.parse.outputs.semVer }}
      - name: Output major
        run: echo ${{ steps.parse.outputs.semVerMajor }}
      - name: Output minor
        run: echo ${{ steps.parse.outputs.semVerMinor }}
      - name: Output patch
        run: echo ${{ steps.parse.outputs.semVerPatch }}
      - name: Output prerelease
        run: echo ${{ steps.parse.outputs.semVerPreRelease }}
      - name: Output buildmetadata
        run: echo ${{ steps.parse.outputs.semVerBuildMetadata }}
      - name: Output majorMinorOnly
        run: echo ${{ steps.parse.outputs.majorMinorOnly }}
  happy-path-without-v:
    runs-on: ubuntu-latest
    name: Happy Path without v prefix
    steps:
      - name: SemVer parse
        id: parse
        uses: NetChris-actions/parse-semver@1-init
        with:
          parseValue: '3.2.4-x+d'
      - name: Output full match
        run: echo ${{ steps.parse.outputs.semVer }}
      - name: Output major
        run: echo ${{ steps.parse.outputs.semVerMajor }}
      - name: Output minor
        run: echo ${{ steps.parse.outputs.semVerMinor }}
      - name: Output patch
        run: echo ${{ steps.parse.outputs.semVerPatch }}
      - name: Output prerelease
        run: echo ${{ steps.parse.outputs.semVerPreRelease }}
      - name: Output buildmetadata
        run: echo ${{ steps.parse.outputs.semVerBuildMetadata }}
      - name: Output majorMinorOnly
        run: echo ${{ steps.parse.outputs.majorMinorOnly }}
  major-minor-only:
    runs-on: ubuntu-latest
    name: Major.Minor only
    steps:
      - name: SemVer parse
        id: parse
        uses: NetChris-actions/parse-semver@1-init
        with:
          parseValue: 'v78.23'
      - name: Output full match
        run: echo ${{ steps.parse.outputs.semVer }}
      - name: Output major
        run: echo ${{ steps.parse.outputs.semVerMajor }}
      - name: Output minor
        run: echo ${{ steps.parse.outputs.semVerMinor }}
      - name: Output patch
        run: echo ${{ steps.parse.outputs.semVerPatch }}
      - name: Output prerelease
        run: echo ${{ steps.parse.outputs.semVerPreRelease }}
      - name: Output buildmetadata
        run: echo ${{ steps.parse.outputs.semVerBuildMetadata }}
      - name: Output majorMinorOnly
        run: echo ${{ steps.parse.outputs.majorMinorOnly }}
  sad-path:
    runs-on: ubuntu-latest
    name: Sad Path
    steps:
      - name: SemVer parse
        id: parse
        uses: NetChris-actions/parse-semver@1-init
        with:
          parseValue: 'this-is-a-bad-version'
      - name: Output full match
        run: echo ${{ steps.parse.outputs.semVer }}
      - name: Output major
        run: echo ${{ steps.parse.outputs.semVerMajor }}
      - name: Output minor
        run: echo ${{ steps.parse.outputs.semVerMinor }}
      - name: Output patch
        run: echo ${{ steps.parse.outputs.semVerPatch }}
      - name: Output prerelease
        run: echo ${{ steps.parse.outputs.semVerPreRelease }}
      - name: Output buildmetadata
        run: echo ${{ steps.parse.outputs.semVerBuildMetadata }}
      - name: Output majorMinorOnly
        run: echo ${{ steps.parse.outputs.majorMinorOnly }}
