on: [push]

jobs:
  happy-path-with-v:
    runs-on: ubuntu-latest
    name: 
    steps:
      - name: SemVer parse
        id: parse
        uses: NetChris-actions/parse-semver@1-init
        with:
          version-input: 'v1.2.3'
      - name: Get the outputs
        run: echo "The time was ${{ steps.parse.outputs.all }}"
