on: [push]

jobs:
  happy-path-with-v:
    runs-on: ubuntu-latest
    name: 
    steps:
      - name: SemVer parse
        id: parse
        uses: NetChris-actions/parse-semver@1-init
        with:
          parseValue 'v1.2.3'
      - name: Output full match
        run: echo ${{ steps.parse.outputs.semVer }}
      - name: Output major
        run: echo ${{ steps.parse.outputs.semVerMajor }}
      - name: Output minor
        run: echo ${{ steps.parse.outputs.semVerMinor }}
      - name: Output patch
        run: echo ${{ steps.parse.outputs.semVerPatch }}
      - name: Output prerelease
        run: echo ${{ steps.parse.outputs.semVerPreRelease }}
      - name: Output buildmetadata
        run: echo ${{ steps.parse.outputs.semVerBuildMetadata }}
  happy-path-without-v:
    runs-on: ubuntu-latest
    name: 
    steps:
      - name: SemVer parse
        id: parse
        uses: NetChris-actions/parse-semver@1-init
        with:
          parseValue '3.2.1'
      - name: Output full match
        run: echo ${{ steps.parse.outputs.semVer }}
      - name: Output major
        run: echo ${{ steps.parse.outputs.semVerMajor }}
      - name: Output minor
        run: echo ${{ steps.parse.outputs.semVerMinor }}
      - name: Output patch
        run: echo ${{ steps.parse.outputs.semVerPatch }}
      - name: Output prerelease
        run: echo ${{ steps.parse.outputs.semVerPreRelease }}
      - name: Output buildmetadata
        run: echo ${{ steps.parse.outputs.semVerBuildMetadata }}
  sad-path:
    runs-on: ubuntu-latest
    name: 
    steps:
      - name: SemVer parse
        id: parse
        uses: NetChris-actions/parse-semver@1-init
        with:
          parseValue 'this_is_not-a-version'
      - name: Output full match
        run: echo ${{ steps.parse.outputs.semVer }}
      - name: Output major
        run: echo ${{ steps.parse.outputs.semVerMajor }}
      - name: Output minor
        run: echo ${{ steps.parse.outputs.semVerMinor }}
      - name: Output patch
        run: echo ${{ steps.parse.outputs.semVerPatch }}
      - name: Output prerelease
        run: echo ${{ steps.parse.outputs.semVerPreRelease }}
      - name: Output buildmetadata
        run: echo ${{ steps.parse.outputs.semVerBuildMetadata }}
